version: 2.1

orbs:
  maven: circleci/maven@0.0.12

workflows:
  maven_test:
    jobs:
    #  - maven/test # checkout, build, test, and upload test results
     - run: mvn install -DskipTests
     - run: mvn dependency:go-offline

     - save_cache:
       paths:
         - ~/.m2
         key: v1-dependencies-{{ checksum "pom.xml" }}

     # run tests!
     - run: mvn install
     - run: mvn integration-test
